### ISSUE TITLE
Adding SignalR extension breaks dependency injection

### ISSUE THREAD

**Issue by MatthijsvdVeer** [Azure/azure-functions-signalrservice-extension#126] opened 2020-08-17 09:30 UTC
I have a project with a Function on an HTTP trigger. I use dependency injection to inject some dependencies. When I add the SignalR package, even if I don't use it or configure it, dependency injection stops working. This occurs both locally and online.

I created [this sample project](https://github.com/MatthijsvdVeer/FunctionsSignalRIssue) to illustrate the issue. In its current state, it will fail, but remove the package and it works.

## Reproduction steps
Create a new Functions project (netcore 3.1) with an HTTP trigger and configure dependency injection.
Publish the Function (consumption plan, North Europe
Trigger the Function, the Function will respond.

Add the following NuGet package: Microsoft.Azure.WebJobs.Extensions.SignalRService Version="1.2.0"
Publish the Function again
Trigger the Function, Function will return a HTTP 500.

## Logs:
```
2020-08-17T09:17:10.089 [Error] Executed 'Function1' (Failed, Id=8b71eb16-d675-42e0-9a8b-75e2e8de75f3, Duration=7ms)
System.InvalidOperationException : Unable to resolve service for type 'FunctionApp2.IEchoService' while attempting to activate 'FunctionApp2.Function1'.
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetService(IServiceProvider sp,Type type,Type requiredBy,Boolean isDefaultParameterRequired)
   at lambda_method(Closure ,IServiceProvider ,Object[] )
   at Microsoft.Azure.WebJobs.Host.Executors.DefaultJobActivator.CreateInstance[T](IServiceProvider serviceProvider) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\DefaultJobActivator.cs : 37
   at Microsoft.Azure.WebJobs.Host.Executors.DefaultJobActivator.CreateInstance[T](IFunctionInstanceEx functionInstance) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\DefaultJobActivator.cs : 32
   at Microsoft.Azure.WebJobs.Host.Executors.ActivatorInstanceFactory`1.<>c__DisplayClass1_1.<.ctor>b__0(IFunctionInstanceEx i) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\ActivatorInstanceFactory.cs : 20
   at Microsoft.Azure.WebJobs.Host.Executors.ActivatorInstanceFactory`1.Create(IFunctionInstanceEx functionInstance) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\ActivatorInstanceFactory.cs : 26
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`2.CreateInstance(IFunctionInstanceEx functionInstance) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionInvoker.cs : 44
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ParameterHelper.Initialize() at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs : 846
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.TryExecuteAsyncCore(IFunctionInstanceEx functionInstance,CancellationToken cancellationToken) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs : 122
```

**Comment by Stephan-Hoffmann** [comment] 2020-09-15 14:41
Damn, I just noticed the same thing... I dont suppose you have a solution for this problem yet????

**Comment by MatthijsvdVeer** [comment] 2020-09-15 15:04
I haven't found a solution and changed my function to not use DI. But I did recently stumble upon a sample that uses SignalR and DI without any issues. I haven't had time to check the differences, but it's [here](https://github.com/Azure-Samples/digital-twins-explorer/blob/master/functions/Functions.csproj). Might be because they use version 1.1.0

**Comment by Stephan-Hoffmann** [comment] 2020-09-15 16:23
Right - so I have found a workaround. Maybe that helps someone to find the right solution....

I added a file called 'extensions.json' to my project, and made to copy always on build. It contains this code

```
{
  "extensions": [
    {
      "name": "SignalR",
      "typeName": "Microsoft.Azure.WebJobs.Extensions.SignalRService.SignalRWebJobsStartup, Microsoft.Azure.WebJobs.Extensions.SignalRService, Version=1.2.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60"
    },
    {
      "name": "MyProject",
      "typeName": "MyProject.MyStartup, MyFunctions, Version=3.0.0.0"
    }
  ]
}
```

With this, both extensions (SignalR and mine) are called.

**Comment by Stephan-Hoffmann** [comment] 2020-09-16 10:12
The above doesnt work when publishing to Azure. 
I ended up debugging the build process and found that the discovering of extensions failed for my assembly because there was a dependency not found (UserSecrets in my case). 
Although I am not using those, after referencing them the extensions started to build correctly and all my DI is working fine again.

**Comment by Y-Sindo** [comment] 2021-08-30 03:13
@anttlcc What's your SignalR extension version ?

**Comment by circuitrider** [comment] 2022-08-08 00:45
SignalRWebJobsStartup shouldn't exist, documentation should instruct consumer to configure it as any other dependency would be done.

I am working around this by eliminating the need for DI in my signalr functions app. Just going to have it send/receive messages on service bus to other function apps doing the heavier server side work where the DI provides actual value.

Has nice added benefit of keeping active connections to a minimum since they don't live as long in the signalr functions.

**Comment by Y-Sindo** [comment] 2022-08-08 02:27
@circuitrider Do you mean that you have problem with `SignalRWebJobsStartup`? Could you provide a complete project to reproduce the problem?

**Comment by Y-Sindo** [comment] 2022-08-08 03:04
@MatthijsvdVeer I updated the sample to functions v4, using latest functions SDK and SignalR extensions, adding `local.settings.json`, and everything worked well.

**Comment by circuitrider** [comment] 2022-08-08 05:32
Not hitting anything in my startup. Looks like SignalRWebJobsStartup is being activated instead since it was loaded last.

[signalR_DIRepro.zip](https://github.com/Azure/azure-functions-signalrservice-extension/files/9278949/signalR_DIRepro.zip)

**Comment by Y-Sindo** [comment] 2022-08-08 08:04
@circuitrider I set a breakpoint in your startup in VS and it was hit. How do you know your startup was not hit?  And what your startup does is repeating the default settings. HttpClient is injected by default.

**Comment by circuitrider** [comment] 2022-08-08 15:47
So apparently this is a problem with my VS code not properly attaching to the debugger. Disregard my issue, thanks for your time.

**Comment by Y-Sindo** [comment] 2022-08-09 04:02
As the original issue is old and cannot be reproduced in latest functions SDK and SignalR extensions, I will close it.

**Closed by Y-Sindo** 2022-08-09 04:02 UTC
